website/views.py
import datetime
import os
from datetime import timedelta
import cx_Oracle
import oracledb
from dotenv import load_dotenv
from flask import (Blueprint, flash, redirect, render_template, request, 
                   session, url_for)
from flask_bcrypt import check_password_hash
from flask_login import current_user, login_required, login_user, logout_user
from sqlalchemy.exc import (DatabaseError, DataError, IntegrityError,
                            InterfaceError, InvalidRequestError)
from werkzeug.routing import BuildError


from . import bcrypt, db, login_manager
from .forms import login_form, register_form
from .models import User

views = Blueprint('views', __name__)

load_dotenv()

un = os.getenv('ADMIN')
pw = os.getenv('PASSWORD')
host = os.getenv('HOST')
port = os.getenv('PORT')
sid = os.getenv('SID')
sid = cx_Oracle.makedsn(host, port, sid=sid)
pool = oracledb.create_pool(user=un, password = pw, dsn=sid, min=2, max=5, increment=1)

@login_manager.user_loader
def load_user(member_id):
    return User.query.get(int(member_id))

@views.before_request
def session_handler():
    session.permanent = True
    views.permanent_session_lifetime = timedelta(minutes=1)

@views.route("/shop", methods=("GET", "POST"), strict_slashes=False)
@login_required
def shop():
    with pool.acquire() as connection:
        with connection.cursor() as cursor:
                q1 = """SELECT * FROM bike INNER JOIN category ON bike.category_id = category.category_id INNER JOIN manufacturer ON bike.manufacturer_id = manufacturer.manufacturer_id ORDER BY bike_id"""
                cursor.execute(q1)
                product_data = cursor.fetchall()
    return render_template("shop.html", data = product_data, user=current_user)

@views.route("/checkout/<int:id>", methods=("GET", "POST"), strict_slashes=False)
@login_required
def checkout(id:int):
    with pool.acquire() as connection:
        with connection.cursor() as cursor:
            customer_data = cursor.execute("""SELECT num_rentals, unpaid_balance FROM customer WHERE customer.member_id=:member_id""", member_id = current_user.member_id).fetchall()
    if request.method == "POST":
                months = { '1': 'JAN', '2': 'FEB', '3': 'MAR', '4': 'APR', '5': 'MAY', '6': 'JUN', '7': 'JUL','8': 'AUG','9': 'SEP','10': 'OCT','11': 'NOV', '12': 'DEC' }
                member_id = current_user.member_id
                bike_id = request.url
                if request.form['submit_button'] == 'Return': # return button
                    return_location = request.form.get("store") # from select field
                    return_date = request.form.get("returndate") # As DD-MM-YYYY format
                    split_date = return_date.split('-')
                    new_date_str = [split_date[0], months[f"{split_date[1]}"], split_date[2]]
                    oracle_date = '-'.join(new_date_str)
                    days = None
                    with pool.acquire() as connection:
                        cursor = connection.cursor()
                        update_cust_rentals = """UPDATE customer SET customer.num_rentals = (SELECT num_rentals -1 FROM customer WHERE customer.member_id =:1)""" 
                        update_bike_status = """UPDATE bike SET bike.status = 'in' WHERE bike.bike_id = :1""" 
                        update_bike_location = """UPDATE bike SET bike.location_id = :1 WHERE bike.bike_id = :2""" 
                        update_act_return = """UPDATE rental_detail SET act_return =:1 WHERE rental_id = (SELECT rental_id FROM rental_bike WHERE bike_id = :2 AND member_ID = :3 AND rental_status = 'incomplete')"""
                        update_location_return = """UPDATE rental_detail SET location_return = :1 WHERE rental_id = (SELECT rental_id FROM rental_bike WHERE bike_id = :2 AND member_id = :3 AND rental_status = 'incomplete')"""
                        update_balance = """UPDATE customer SET unpaid_balance = (SELECT unpaid_balance FROM customer WHERE customer.member_id = :1) + (SELECT late_fee from rental_detail WHERE rental_id = (SELECT rental_id FROM rental_bike WHERE bike_id = :2 AND member_id = :3 AND rental_status = 'incomplete'))""" 
                        update_rental_status = """UPDATE rental_bike SET rental_status = 'complete' WHERE rental_id = (SELECT rental_id FROM rental_bike WHERE bike_id = :1 AND member_id = :2 AND rental_status = 'incomplete')"""
                        cursor.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS'") 
                        cursor.execute(update_act_return, [oracle_date, int(bike_id[-1])+1, current_user.member_id]) 
                        cursor.execute(update_location_return,[return_location, int(bike_id[-1])+1, current_user.member_id])
                        cursor.execute(update_bike_location, [return_location, int(bike_id[-1])+1]) 
                        cursor.execute(update_cust_rentals, [current_user.member_id]) 
                        cursor.execute(update_balance, [current_user.member_id, int(bike_id[-1])+1, current_user.member_id]) 
                        cursor.execute(update_bike_status, [int(bike_id[-1])+1]) 
                        cursor.execute(update_rental_status, [int(bike_id[-1])+1, current_user.member_id])
                        connection.commit()
                elif request.form['submit_button'] == 'Checkout':
                    days = request.form.get("quantity") # days 
                    with pool.acquire() as connection:
                        cursor = connection.cursor() 
                        cursor.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS'")
                        insert_rental = """INSERT INTO rental_bike (member_id, bike_id, rented_out, days_out, rental_status) VALUES(:1, :2, :3, :4, :5)"""
                        add_rental = """UPDATE customer set num_rentals = (SELECT num_rentals + 1 FROM customer WHERE member_id =:1)"""
                        try:
                            cursor.execute(add_rental, [current_user.member_id])
                            cursor.execute(insert_rental, [current_user.member_id, int(bike_id[-1])+1, datetime.datetime.now(), days, 'incomplete'])
                            connection.commit()
                        except oracledb.IntegrityError:
                            db.session.rollback()
                            flash(f"Maximum number of rentals reached.", "warning")
                            return redirect(url_for('views.checkout', id=int(bike_id[-1])))
                        except oracledb.DatabaseError as e:
                            error_obj, = e.args  
                            flash("Maximum account balance reached.", "warning")
                            db.session.rollback()
                            return redirect(url_for('views.checkout', id=int(bike_id[-1])))
                if days != None:
                    return redirect(url_for('views.shop'))
                    # return render_template("blank.html", p = " num_rentals: " + str(customer_data[0][0])  + " days: " + str(days) + " member_id: " + str(member_id) + " bike_id: " + str(int(bike_id[-1])+1))
                
                else:
                    return redirect(url_for('views.shop'))
                    # return render_template("blank.html", p =  str(customer_data[0])+ "  " +  "return_date: " + str(oracle_date) + " return_location: " + str(return_location)+ " member_id: " + str(member_id)+ " bike_id: "  + str(int(bike_id[-1])+1))
    elif request.method == "GET":
        q1 = """SELECT * FROM bike INNER JOIN category ON bike.category_id = category.category_id INNER JOIN manufacturer ON bike.manufacturer_id = manufacturer.manufacturer_id ORDER BY bike_id"""
        q2 = """SELECT location_id, city, state FROM location"""
        with pool.acquire() as connection:
            with connection.cursor() as cursor:
                    cursor.execute(q1)
                    product_data = cursor.fetchall()
                    cursor.execute(q2)
                    location_data = cursor.fetchall()
        return render_template("checkout.html", pdata = product_data[id], isCheckout=True, user=current_user, ldata=location_data)

@views.route("/login/", methods=("GET", "POST"), strict_slashes=False)
def login():
    form = login_form()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if check_password_hash((user.password), form.password.data):
                login_user(user)
                return redirect(url_for('views.shop'))
            else:
                flash("Invalid Username or password!", "danger")
        except Exception as e:
            flash("User not found.", "danger")
    return render_template("auth.html",
        form=form,
        text="Login",
        title="Login",
        btn_action="Login"
        )

# Register route
@views.route("/register/", methods=("GET", "POST"), strict_slashes=False)
def register():
    form = register_form()
    if form.validate_on_submit():
        try:
            fname = form.fname.data
            lname = form.lname.data
            email = form.email.data
            phone = form.phone.data
            address = form.address.data
            password = form.password.data

            newuser = User(
                email=email,
                fname=fname,
                lname=lname,
                phone=phone,
                address=address,
                unpaid_balance = 0,
                num_rentals = 0,
                password=bcrypt.generate_password_hash(password).decode('utf8'),
            )

            db.session.add(newuser)
            db.session.commit()
            flash("Account Creation Successful.", "success")
            return redirect(url_for("views.login"))

        except InvalidRequestError:
            db.session.rollback()
            flash(f"Something went wrong!", "danger")
        except IntegrityError:
            db.session.rollback()

website/templates/account.html
{% extends "index.html" %}

{% block content %}
<div role="main" class="main shop pt-4">
		<div class="container">
          <h1>Account</h1>
                <hr>
			<div id="table"></div>
      <form enctype="multipart/form-data" method="POST" class="cart" action="#">
        <div class="row">
        <button type="submit"  name="submit_button" value="Balance" class="btn btn-dark btn-modern text-uppercase bg-color-hover-primary border-color-hover-primary mt-5 ml-3">Pay Balance</button>
        </form>
        </div>
</div>

<script src="{{ url_for('static', filename='js/gridjs.umd.js') }}"></script>
  
<!-- Page specific script -->
<script>
      const tableDiv = document.getElementById('table');

      const updateUrl = (prev, query) => {
        return prev + (prev.indexOf('?') >= 0 ? '&' : '?') + new URLSearchParams(query).toString();
      };

      const editableCellAttributes = (data, row, col) => {
          if (row) {
            return {contentEditable: 'true', 'data-element-id': row.cells[0].data};
          }
          else {
            return {};
          }
      };

      new gridjs.Grid({
        columns: [
          { id: 'member_id', 'hidden': true },
          { id: 'fname', name: 'First', width: '145px',},
          { id: 'lname', name: 'Last', width: '145px',},
          { id: 'email', name: 'Email'},
          { id: 'password', 'hidden': true},
          { id: 'address', name: 'Address',width: '175px' },
          { id: 'phone', name: 'Phone'},
          { id: 'registration_date','hidden': true },
          { id: 'num_rentals', name: 'Rentals', width: '145px'},
          { id: 'unpaid_balance', name: 'Balance', width: '145px'},


        ],
        server: {
          url: '/api/data/user',
          then: results => results.data,
          total: results => results.total,
        },
        search: {
          enabled: false,
          server: {
            url: (prev, search) => {
              return updateUrl(prev, {search});
            },
          },
        },
        pagination: {
          enabled: false,
          server: {
            url: (prev, page, limit) => {
              return updateUrl(prev, {start: page * limit, length: limit});
            },
          },
        },
      }).render(tableDiv);


    </script>
 {% endblock %}	

website/templates/auth.html
{% extends "base.html" %}
{% block title%} {{ title }} {% endblock %}
{% block content%}
<div class="container">
    <div class="row mt-4">
        <div class="col-lg-5 col-md-6 m-auto card p-4">
            <form action="{{ request.path }}" method="POST" class="card-body">
                {{ form.csrf_token }}

                {% with messages = get_flashed_messages(with_categories=true) %}
                <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}

                <div class="text-center">
                    <h2>Pathway Biking</h2>
                    <h5 class="text-primary">{{ text }}</h5>
                </div>
                
                {% if request.path == '/register/' %}
                <div class="form-group mb-3">
                    {{ form.fname(class_="form-control",placeholder="First Name",required='required')}}
                </div>
                <div class="form-group mb-3">
                    {{ form.lname(class_="form-control",placeholder="Last Name",required='required')}}
                </div>
                <div class="form-group mb-3">
                    {{ form.phone(class_="form-control",placeholder="Phone Number",required='required')}}
                </div>
                <div class="form-group mb-3">
                    {{ form.address(class_="form-control",placeholder="Address",required='required')}}
                </div>
                {% endif%}
                <div class="form-group mb-3">
                    {{ form.email(class_="form-control",placeholder="Email",required='required')}}
                </div>
                {% for error in form.email.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor%}
                <div class="form-group mb-3">
                    {{ form.password(class_="form-control",placeholder="Password",required='required')}}
                </div>
                {% for error in form.password.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> {% endfor%}
                {% if request.path == '/register/' %}
                <div class="form-group mb-3">
                    {{ form.cpwd(class_="form-control",placeholder="Confirm Password",required='required')}}
                </div>
                {% for error in form.cpwd.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> {% endfor%}
                {% endif %}
                <div class="text-center">

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-block btn-primary mb-3"id="registerme"> {{ btn_action }} </button>
                    </div>

                    <p>
                        {% if request.path != '/register/' %}
                        New here?
                        <a href="{{url_for('views.register')}}" id="register">Create account</a>
                        {% else %}
                        Already have an account?
                        <a href="{{url_for('views.login')}}">Login</a>
                        {% endif %}
                    </p>
                    
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/adminlte.min.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Sweet alert Js -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      

    <title> {% block title%} {{ title }} {% endblock %} </title>
</head>

<body>
    <div class="hold-transition login-page">
        {% block content%}
        {% endblock %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

website/templates/blank.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HTML 5 Boilerplate</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
  <p>{{p}}</p>
	<script src="index.js"></script>
  </body>
</html>

website/templates/checkout.html
{% extends "index.html" %}
{% block content%}
<div role="main" class="main shop pt-4">
				<div class="container">
					<div class="row">
						<div class="col-md-5 mb-5 mb-md-0">

						</div>
                        <div class="row">
						<div class="col-md-5 mb-5 mb-md-0">

							<div class="thumb-gallery-wrapper">
							<a href="{{url_for('static', filename='img/products/' + pdata[3])}}" target="_blank">
										<img alt="" class="img-fluid" src="{{url_for('static', filename='img/products/' + pdata[3])}}" data-zoom-image="img/products/product-grey-7.jpg">	
										</a>
							</div>
						</div>
						<div class="col-md-7">
							<div class="summary entry-summary position-relative">	
								<h1 class="mb-0 font-weight-bold text-7">{{pdata[1]}}</h1>
								<div class="pb-0 clearfix d-flex align-items-center">
									<div title="Rated 3 out of 5" class="float-start">
										<input type="text" class="d-none" value="3" title="" data-plugin-star-rating data-plugin-options="{'displayOnly': true, 'color': 'primary', 'size':'xs'}">
									</div>
								</div>
								<div class="divider divider-small">
									<hr class="bg-color-grey-scale-4">
								</div>
								<p class="price mb-3">
									<span class="sale text-color-dark">${{pdata[5]}}.00</span>
									<span class="amount">${{(pdata[5]|float * 1.20)|int}}.00</span>
								</p>
								<p class="text-3-5 mb-3">{{pdata[2]}}</p>
								<ul class="list list-unstyled text-2">
									<li class="mb-0">AVAILABILITY: <strong class="text-color-dark">{{pdata[4].upper()}}</strong></li>
									{% with messages = get_flashed_messages(with_categories=true) %}
                				<!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
                					 {% if messages %}
                					{% for category, message in messages %}
        				<div class="alert alert-{{category}} alert-dismissible fade show mt-3" role="alert">
                   								 {{ message }}
                									</div>
                					{% endfor %}
                					{% endif %}
                					{% endwith %}
									 {% if pdata[4] != 'in'%}
									<li class="mt-2"><a href="#" onclick="toggleVisible(); return False;"><strong class="text-color-dark" id="returning">Returning?</strong></li></a>
								</ul>
								<script type="text/javascript">
                             function toggleVisible() {
  							var x = document.getElementById("return");
  								if (x.style.display === "none") {
    									x.style.display = "block";
  								} else {
    									x.style.display = "none";
  																}
												}
                                   </script>
								   {% elif pdata[4] != 'out'%}
								<form enctype="multipart/form-data" method="POST" class="cart" action="#">
									<hr>
                                    <ul class="list list-unstyled text-2">
									<strong class="text-color-dark">How Many Days?</strong></li>
								    </ul>
									<div class="quantity quantity-lg">
										<input type="button" class="minus text-color-hover-light bg-color-hover-primary border-color-hover-primary" value="-">
										<input type="text" class="input-text qty text" id="days" title="Qty" value="1" name="quantity" min="1" step="1">
										<input type="button" class="plus text-color-hover-light bg-color-hover-primary border-color-hover-primary" value="+">
									</div>
									<button type="submit"name="submit_button" value="Checkout" class="btn btn-dark btn-modern text-uppercase bg-color-hover-primary border-color-hover-primary">Check Out</button>
								</form>
								   {% endif %} 
									<hr>
									<div class="d-flex align-items-center mb-4">
									<ul class="social-icons social-icons-medium social-icons-clean-with-border social-icons-clean-with-border-border-grey social-icons-clean-with-border-icon-dark me-3 mb-0">
										<!-- Facebook -->
										<li class="social-icons-facebook">
											<a href="http://www.facebook.com/sharer.php?u=https://www.okler.net" target="_blank" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="top" title="Share On Facebook">
												<i class="fab fa-facebook-f"></i>
											</a>
										</li>
										<!-- Google+ -->
										<li class="social-icons-googleplus">
											<a href="https://plus.google.com/share?url=https://www.okler.net" target="_blank" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="top" title="Share On Google+">
												<i class="fab fa-google-plus-g"></i>
											</a>
										</li>
										<!-- Twitter -->
										<li class="social-icons-twitter">
											<a href="https://twitter.com/share?url=https://www.okler.net&amp;text=Simple%20Share%20Buttons&amp;hashtags=simplesharebuttons" target="_blank" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="top" title="Share On Twitter">
												<i class="fab fa-twitter"></i>
											</a>
										</li>
										<!-- Email -->
										<li class="social-icons-email">
											<a href="mailto:?Subject=Share This Page&amp;Body=I%20saw%20this%20and%20thought%20of%20you!%20 https://www.okler.net" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="top" title="Share By Email">
												<i class="far fa-envelope"></i>
											</a>
										</li>
									</ul>
									<a href="#" class="d-flex align-items-center text-decoration-none text-color-dark text-color-hover-primary font-weight-semibold text-2">
										<i class="far fa-heart me-1 ml-1 mr-1"></i> SAVE TO WISHLIST
									</a>
								</div>
								<div class="card mb-2"style="display:none"id="return">
									<div class="card-body">
										<div class="row">
											<div class="col">
											  	<form class="contact-form" enctype="multipart/form-data" action="#" method="POST">
													<div class="row">
													</div>
													<div class="row">
														<div class="form-group col">
															<label class="form-label mb-1 text-2"> Which Store?</label>
															<div class="custom-select-1">
													      		<select class="form-select form-control h-auto py-2" data-msg-required="Please select a store." name="store" required>
													        		<option value="">Choose...</option>
																	{% for item in ldata%}
													        		<option value="{{item[0]}}">{{item[1]}} , {{item[2]}}</option>
																	{% endfor %}
													      		</select>
													      	</div>
														</div>
													</div>
													<div class="row">
														<div class="form-group col">
															<label class="form-label mb-1 text-2">Date of Return</label>
															<input type="text" data-format="**-**-****" data-mask="DD-MM-YYYY" value="" maxlength="12" class="form-control text-3 h-auto py-2" name="returndate" required>
														</div>
													</div>
												<div class="row">
														<div class="form-group col">
															<input type="submit" name="submit_button" value="Return" class="btn btn-dark btn-modern text-uppercase bg-color-hover-primary border-color-hover-primary">
														</div>
											    </div>
								          		</form> 
											</div>
										</div>
									</div>
								</div>
		     				</div>
						 </div>
	     			</div>
				</div>
			</div> 
{% endblock %}

website/templates/shop.html
{% extends "index.html" %}
{% block content%}
			<div role="main" class="main shop pt-4">
				<div class="container">
					<div class="masonry-loader masonry-loader-showing">
						<div class="row products product-thumb-info-list" data-plugin-masonry data-plugin-options="{'layoutMode': 'fitRows'}">
                        {% for item in data%}
							<div class="col-12 col-sm-6 col-lg-3">
								<div class="product mb-0">
									<div class="product-thumb-info border-0 mb-3">
										<div class="product-thumb-info-badges-wrapper">
										</div>
										<a href="{{url_for('views.checkout', id=item[0] - 1)}}">
											<div class="product-thumb-info-image product-thumb-info-image-effect">
												<img alt="" class="img-fluid" src="{{url_for('static', filename='img/products/' + item[3] )}}">
												<img alt="" class="img-fluid" src="{{url_for('static', filename='img/products/' + item[3] )}}">
											</div>
										</a>
									</div>
									<div class="d-flex justify-content-between">
										<div>
											<a href="#" class="d-block text-uppercase text-decoration-none text-color-default text-color-hover-primary line-height-1 text-0 mb-1">{{item[12]}}</a>
											<h3 class="text-3-5 font-weight-medium font-alternative text-transform-none line-height-3 mb-0"><a href="shop-product-sidebar-right.html" class="text-color-dark text-color-hover-primary">{{item[1]}}</a></h3>
										</div>
									</div>
									<p class="price text-5 mb-3">
										<span class="sale text-color-dark font-weight-semi-bold">${{item[5]}}</span>
										<span class="amount">${{(item[5]|float * 1.20)|int}}</span>
									</p>
								</div>
							</div>
						   {% endfor %}
                        </div>
				</div>
		</div>
</div>
{% endblock %}